apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.fullname" . }}-service
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}

  selector:
    {{- include "python-app.selectorLabels" . | nindent 4 }}
